default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages: [pre-commit]

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [chore, docs, feat, fix, refactor, revert, test]
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff linter
        description: "Uses Ruff to lint and fix Python code."
        entry: pipenv run ruff check --fix .
        language: system
        types: [python]
      - id: ruff-format
        name: Ruff formatter
        description: "Uses Ruff to format Python code using standard conventions."
        entry: pipenv run ruff format .
        language: system
        types: [python]
      - id: run-unit-tests
        name: Run unit tests
        description: "Run unit tests locally to ensure all tests pass before committing code."
        entry: pipenv run pytest --cov=lambdas tests/unit --cov-report=term-missing -vv
        language: system
        types: [python]
        pass_filenames: false
        files: ^lambdas/.*
      - id: run-e2e-tests
        name: Run E2E tests
        description: "Run E2E tests."
        entry: pipenv run behave -v --no-capture tests/e2e
        language: system
        types: [python]
        pass_filenames: false
        files: ^lambdas/.*
