default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages: [pre-commit]

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [chore, docs, feat, fix, refactor, revert, test]
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff linter
        description: "Uses Ruff to lint and fix Python code."
        entry: pipenv run ruff check --fix .
        language: system
        types: [python]
      - id: ruff-format
        name: Ruff formatter
        description: "Uses Ruff to format Python code using standard conventions."
        entry: pipenv run ruff format .
        language: system
        types: [python]
